baseurl: /desmoines
permalink: pretty
markdown: kramdown
paginate: 5
repo: desmoines
github_org: maptime
maptime:
  chapter: MaptimeDSM
  twitter: TwitterHandle
  #disqus: YOUR DISQUS USERNAME

gems:
  - jekyll-feed
